export const recitersMap = new Map();
recitersMap.set("AbdulBaset AbdulSamad [Mujawwad]", "abdulbasitmujawwad");
recitersMap.set("AbdulBaset AbdulSamad [Murattal]", "abdulbasitmurattal");
recitersMap.set("Mishary Rashid Alafasy", "alafasy");
recitersMap.set("Ayman Swed", "aymanswed");
recitersMap.set("Bandar Balila", "bandarbalila");
recitersMap.set("Laayoun El Kouchi", "laayounelkouchi");
recitersMap.set("Mohamed Al-Tablawi", "mohamedtablawi");
recitersMap.set(
  "Muhammad Siddeeq al-Minshawi [Mujawwad]",
  "muhammadsiddiqalminshawimujawwad"
);
recitersMap.set("Mostafa Ismaeel", "mustafaismail");
recitersMap.set("Nasser Alqatami", "nasseralqatami");
recitersMap.set("Yasser Al_Dosari", "yasseraldossari");
recitersMap.set("Ra'ad Al-Kurdi", "kurdi");
recitersMap.set("Yasser Salama", "yassersalama");
recitersMap.set("Ahmed ibn Ali al-Ajamy", "ahmedalajmi");
recitersMap.set("Mahmud Ali Al Banna", "mahmoudalialbanna");
recitersMap.set("Mahmoud Khalil Al-Husary", "husr");

//------------------------------------------------------
export const radios = [
  "Mahmoud Khalil Al-Husary",
  "Muhammad Siddeeq al-Minshawi [Mujawwad]",
  "AbdulBaset AbdulSamad [Mujawwad]",
  "AbdulBaset AbdulSamad [Murattal]",
  "Mostafa Ismaeel",
  "Amazing short Recitations",
  "Mix Recitations",
  "Beautiful Recitations",
  "Mishary Rashid Alafasy",
  "Ayman Swed",
  "Bandar Balila",
  "Laayoun El Kouchi",
  "Mohamed Al-Tablawi",
  "Nasser Alqatami",
  "Yasser Al_Dosari",
  "Ra'ad Al-Kurdi",
  "Yasser Salama",
  "Ahmed ibn Ali al-Ajamy",
  "Mahmud Ali Al Banna",
];
//--------------------------------
export const surahs = [
  "Al-Fatihah",
  "Al-Baqarah",
  "Al-Imran",
  "An-Nisa",
  "Al-Ma'idah",
  "Al-An'am",
  "Al-A'raf",
  "Al-Anfal",
  "At-Taubah",
  "Yunus",
  "Hud",
  "Yusuf",
  "Ar-Ra'd",
  "Ibrahim",
  "Al-Hijr",
  "An-Nahl",
  "Al-Isra",
  "Al-Kahf",
  "Maryam",
  "Ta-Ha",
  "Al-Anbiya",
  "Al-Hajj",
  "Al-Mu'minun",
  "An-Nur",
  "Al-Furqan",
  "Ash-Shu'ara",
  "An-Naml",
  "Al-Qasas",
  "Al-'Ankabut",
  "Ar-Rum",
  "Luqman",
  "As-Sajdah",
  "Al-Ahzab",
  "Saba",
  "Fatir",
  "Ya-Sin",
  "As-Saffat",
  "Sad",
  "Az-Zumar",
  "Ghafir",
  "Fussilat",
  "Ash-Shura",
  "Az-Zukhruf",
  "Ad-Dukhan",
  "Al-Jathiya",
  "Al-Ahqaf",
  "Muhammad",
  "Al-Fath",
  "Al-Hujurat",
  "Qaf",
  "Adh-Dhariyat",
  "At-Tur",
  "An-Najm",
  "Al-Qamar",
  "Ar-Rahman",
  "Al-Waqi'ah",
  "Al-Hadid",
  "Al-Mujadila",
  "Al-Hashr",
  "Al-Mumtahanah",
  "As-Saff",
  "Al-Jumu'ah",
  "Al-Munafiqun",
  "At-Taghabun",
  "At-Talaq",
  "At-Tahrim",
  "Al-Mulk",
  "Al-Qalam",
  "Al-Haqqah",
  "Al-Ma'arij",
  "Nuh",
  "Al-Jinn",
  "Al-Muzzammil",
  "Al-Muddaththir",
  "Al-Qiyamah",
  "Al-Insan",
  "Al-Mursalat",
  "An-Naba",
  "an-Naziat",
  "Abasa",
  "At-Takwir",
  "Al-Infitar",
  "Al-Mutaffifin",
  "Al-Inshiqaq",
  "Al-Buruj",
  "At-Tariq",
  "Al-A'la",
  "Al-Ghashiyah",
  "Al-Fajr",
  "Al-Balad",
  "Ash-Shams",
  "Al-Lail",
  "Ad-Dhuha",
  "Al-Inshirah",
  "At-Tin",
  "Al-'Alaq",
  "Al-Qadr",
  "Al-Bayyinah",
  "Az-Zalzalah",
  "Al-'Adiyat",
  "Al-Qari'ah",
  "At-Takathur",
  "Al-'Asr",
  "Al-Humazah",
  "Al-Fil",
  "Quraysh",
  "Al-Ma'un",
  "Al-Kauthar",
  "Al-Kafirun",
  "An-Nasr",
  "Al-Masad",
  "Al-Ikhlas",
  "Al-Falaq",
  "An-Nas",
];
//----------------------------------
export const surahMap = new Map();
surahs.forEach((surah, index) => {
  surahMap.set(surah, index + 1);
});
